branches:
  only:
    - master
    - staging
language: node_js
node_js:
  - "7.1.0"
env: 
  - NODE_ENV=production
install:
  - npm -g install webpack
  - npm install
  - npm -g install jest babel-jest
  - pip install --user -r requirements.txt
script:
  - npm run build
  - npm run lint
  - npm run test
  - python manage.py test
