os: linux
sudo: required
dist: trusty
services:
  - xvfb
language: python
python:
- "2.7"
env:
  - NODE_ENV=production NODE_VERSION="10.23.0"
branches:
  only:
  - master
  - staging
cache:
  apt: true
  directories:
  - node_modules
  - $HOME/.npm
  - $HOME/.cache/pip
install:
- wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
- sudo apt-get clean
- sudo apt-get update
- sudo apt-get install dpkg
- sudo -E apt-get -yq --allow-unauthenticated install google-chrome-stable
- nvm install $NODE_VERSION
- npm -g install chromedriver
- npm -g install jest@20
- npm install
- pip install --upgrade pip
- pip install -r requirements.txt
addons:
#  chrome: stable
#  apt:
#    sources:
#    - google-chrome
#    packages:
#    - google-chrome-stable
  hosts:
  - jhu.sem.ly
before_script:
#- export DISPLAY=:99.0
#- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- npm run build
- npm run lint
- npm run test
- python manage.py test
- make html -C docs
