os: linux
sudo: required
dist: trusty
language: python
python:
- "2.7"
env:
  - NODE_ENV=production NODE_VERSION="11.2.0"
branches:
  only:
  - master
  - staging
cache:
  apt: true
  directories:
  - node_modules
  - $HOME/.npm
  - $HOME/.cache/pip
install:
- nvm install $NODE_VERSION
- npm -g install webpack
- npm -g install chromedriver
- npm -g install jest babel-jest
- npm install
- pip install --upgrade pip
- pip install -r requirements.txt
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  hosts:
  - jhu.sem.ly
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- npm run build
- npm run lint
- npm run test
- python manage.py test
- make html -C docs
