os: linux
sudo: required
dist: trusty
language: node_js
node_js:
- 7.1.0
python:
- "3.5"
env:
  global:
    - NUMPY_VERSION=1.13.1
    - SCIPY_VERSION=0.19.1
    - REQST_VERSION=2.18.4
    - NODE_ENV=production
branches:
  only:
  - master
  - staging
cache:
  apt: true
  directories:
  - node_modules
  - $HOME/.npm
  - $HOME/.cache/pip
before_install:
- sudo apt-get update
- sudo apt-get -y install python3 python3-pip
- sudo pip3 install --upgrade pip
install:
- npm -g install webpack
- npm -g install chromedriver
- npm -g install jest babel-jest
- npm install
- pip3 install --user numpy==$NUMPY_VERSION
- pip3 install --user scipy==$SCIPY_VERSION
- pip3 install --user requests==$REQST_VERSION
- pip3 install --user -r requirements.txt
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  hosts:
  - jhu.sem.ly
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- npm run build
- npm run lint
- npm run test
- python3 manage.py test
- make html -C docs
