apiVersion: v1
kind: Service
metadata:
  name: semesterly-service
  namespace: semesterly-dev
spec:
  selector:
    app: semesterly
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
